service: apollo-lambda
provider:
  name: aws
  runtime: nodejs20.x
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: dist/app.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true